# numpy_exercises

In [254]:
import numpy as np

### Use the following code for the questions below:






In [428]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [256]:
# Option 1

negative_numbers = a < 0
negative_numbers
print(a[negative_numbers])
len(a[negative_numbers])

[-2 -1 -6 -7]


4

In [257]:
# Option 2

len(a[a < 0])

4

### 2. How many positive numbers are there?



In [224]:
# Option 1

positive_numbers = a > 0
positive_numbers
print(a[positive_numbers])
len(a[positive_numbers])

[ 4 10 12 23  3]


5

In [258]:
# Option 2

len(a[a > 0])

5

### 3. How many even positive numbers are there?



In [215]:
# Option 1

even_numbers = a % 2 == 0
positive_numbers = a > 0
even_and_positive = even_numbers & positive_numbers
print(a[even_and_positive])
len(a[even_and_positive])

[ 4 10 12]


3

In [216]:
# Option 2

len(a[(a % 2 == 0) & (a > 0)])

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?



#### brackets are like the verbal word “where” . 
- adding_three where adding_three is greater than zero 
- translates to adding_three[adding_three > 0]

In [222]:
# Option 1

adding_three = a + 3
adding_three
positive_after_three = adding_three > 0
print(adding_three [positive_after_three])

len(adding_three[positive_after_three])

[ 7 13 15 26  1  2  3  3  3  6]


10

In [218]:
# Option 2

len(a[(a + 3) > 0])

10

### 5. If you squared each number, what would the new mean and standard deviation be?



In [417]:
# original mean and standard deviation

np.mean(a), np.std(a)

(3.0, 8.06225774829855)

In [418]:
# Option 1 for new mean and standard deviation after squaring numbers

a_squared = a ** 2
print("The new mean would be:", np.mean(a_squared))
print("The new standard deviation would be:", np.std(a_squared))

The new mean would be: 74.0
The new standard deviation would be: 144.0243035046516


In [419]:
# Option 2

np.mean(a ** 2), np.std(a ** 2)

(74.0, 144.0243035046516)

### 6.  A common statistical operation on a dataset is centering. 
- This means to adjust the data such that 
- the mean of the data is 0. 
- This is done by subtracting the mean from each data point. 
- Center the data set. See this link for more on centering.



In [429]:
# original mean and standard deviation

np.mean(a), np.std(a)

(3.0, 8.06225774829855)

In [430]:
# Option 1

centered_data = a - np.mean(a)
print(centered_data)
print(np.mean(centered_data))
print(np.std(centered_data))

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
0.0
8.06225774829855


In [431]:
# Option 2

a_zscore = ([a - np.mean(a)])

np.mean(a_zscore), np.std(a_zscore)

(0.0, 8.06225774829855)

#### 7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [432]:
# Option 1
# (x - mean) / (std dev)

(a - np.mean(a)) / np.std(a)


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [433]:
# Option 2

import scipy.stats as stats

print(a)
stats.zscore(a)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

- Life w/o numpy to life with numpy
-Use python's built in functionality/operators to determine the following:



In [ ]:
import numpy as np

In [ ]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list



In [277]:
sum_of_a = np.sum(a)
sum_of_a

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list



In [280]:
min_of_a = np.min(a)
min_of_a

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list



In [282]:
max_of_a = np.max(a)
max_of_a

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list



In [285]:
mean_of_a = np.mean(a)
mean_of_a

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together



In [330]:
product_of_a = np.prod(a)
product_of_a

3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]



In [288]:
squares_of_a = [n ** 2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers



In [290]:
odds_in_a = [n for n in a if n % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [292]:
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

# What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [294]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [ ]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [298]:
b = [[3, 4, 5],
     [6, 7, 8]
    ]

b = np.array(b)

In [299]:
sum_of_b = np.sum(b)
sum_of_b

33

### Exercise 2 - refactor the following to use numpy. 

In [300]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [329]:
min_of_b = b.min()
min_of_b

3

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [304]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [328]:
max_of_b = b.max()
max_of_b

8

### Exercise 4 - refactor the following using numpy to find the mean of b

In [306]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [327]:
mean_of_b = b.mean()
mean_of_b 

5.5

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [309]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [325]:
product_of_b = b.prod()
product_of_b

20160

### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [312]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [324]:
squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

### Exercise 7 - refactor using numpy to determine the odds_in_b

In [315]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [323]:
odds_in_b = b[b % 2 != 0]
odds_in_b

array([3, 5, 7])

### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [316]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [322]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

### Exercise 9 - print out the shape of the array b.

In [331]:
b.shape

(2, 3)

### Exercise 10 - transpose the array b.

In [334]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [336]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [340]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [345]:
### Setup 3

# HINT, you'll first need to make sure that the "c" variable 
# is a numpy array prior to using numpy array methods.

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [346]:
c = np.array(c)

### Exercise 1 - Find the min, max, sum, and product of c.



In [352]:
{
"min_c": c.min(), 
"max_c": c.max(),
"sum_c": c.sum(),
"prod_c": c.prod()
}

{'min_c': 1, 'max_c': 9, 'sum_c': 45, 'prod_c': 362880}

### Exercise 2 - Determine the standard deviation of c.

In [361]:
c.std()

2.581988897471611

### Exercise 3 - Determine the variance of c.

In [362]:
c.var()

6.666666666666667

### Exercise 4 - Print out the shape of the array c



In [356]:
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.



In [368]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [369]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Exercise 6 - Get the dot product of the array c with c. 



In [364]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [372]:
(c * c.T).sum()

261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [374]:
(c * c.T).prod()

131681894400

In [375]:
#### Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [376]:
d = np.array(d)

### Exercise 1 - Find the sine of all the numbers in d



In [383]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - Find the cosine of all the numbers in d



In [386]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - Find the tangent of all the numbers in d



In [387]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d



In [388]:
d[d < 0]

array([-90, -30, -45, -45])

### Exercise 5 - Find all the positive numbers in d



In [389]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

### Exercise 6 - Return an array of only the unique numbers in d.



In [390]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.



In [392]:
len(np.unique(d))

11

### Exercise 8 - Print out the shape of d.


In [377]:
d.shape

(3, 6)

### Exercise 9 - Transpose and then print out the shape of d.


In [378]:
d.T.shape

(6, 3)

### Exercise 10 - Reshape d into an array of 9 x 2

In [379]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])